"""Add RepaymentFrequency and CollateralAssumption tables

Revision ID: 54d14c7a38b1
Revises: 3ce2e42d073e
Create Date: 2025-10-05 16:12:55.608571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54d14c7a38b1'
down_revision: Union[str, Sequence[str], None] = '3ce2e42d073e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collateralassumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collateral_description', sa.String(), nullable=False),
    sa.Column('cbn_accepted_collateral_type', sa.String(), nullable=False),
    sa.Column('haircut', sa.Float(), nullable=False),
    sa.Column('time_to_recovery_years', sa.Float(), nullable=False),
    sa.Column('direct_recovery_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateralassumption_collateral_description'), 'collateralassumption', ['collateral_description'], unique=False)
    op.create_table('repaymentfrequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repayment_frequency', sa.String(), nullable=False),
    sa.Column('times_per_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repaymentfrequency_repayment_frequency'), 'repaymentfrequency', ['repayment_frequency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repaymentfrequency_repayment_frequency'), table_name='repaymentfrequency')
    op.drop_table('repaymentfrequency')
    op.drop_index(op.f('ix_collateralassumption_collateral_description'), table_name='collateralassumption')
    op.drop_table('collateralassumption')
    # ### end Alembic commands ###
