"""Add new fields to ECLSummary model

Revision ID: b505345a5404
Revises: fix_email_recipients_id
Create Date: 2025-10-21 21:48:41.410513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b505345a5404'
down_revision: Union[str, Sequence[str], None] = 'fix_email_recipients_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecl_summaries', sa.Column('ead_stage_1', sa.Float(), nullable=True))
    op.add_column('ecl_summaries', sa.Column('ead_stage_2', sa.Float(), nullable=True))
    op.add_column('ecl_summaries', sa.Column('ead_stage_3', sa.Float(), nullable=True))
    op.add_column('ecl_summaries', sa.Column('total_customers', sa.Integer(), nullable=True))
    op.add_column('ecl_summaries', sa.Column('total_ead', sa.Float(), nullable=True))
    op.add_column('ecl_summaries', sa.Column('performing_loan_percentage', sa.Float(), nullable=True))
    op.add_column('ecl_summaries', sa.Column('non_performing_loan_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecl_summaries', 'non_performing_loan_percentage')
    op.drop_column('ecl_summaries', 'performing_loan_percentage')
    op.drop_column('ecl_summaries', 'total_ead')
    op.drop_column('ecl_summaries', 'total_customers')
    op.drop_column('ecl_summaries', 'ead_stage_3')
    op.drop_column('ecl_summaries', 'ead_stage_2')
    op.drop_column('ecl_summaries', 'ead_stage_1')
    # ### end Alembic commands ###
