# generated by fastapi-codegen:
#   filename:  openapi.yml
#   timestamp: 2024-10-08T04:16:59+00:00

from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from ..models import (
    User,
)

from api.database.database import get_db
from api.utils.deps import current_user
from api.schema.user import UpdateMeUser
from ..utils.crud import get_all_users, update_user_info
from ..utils.crud import add_activity
from ..data_model import ActivityTag, User as UserModel

from typing import Annotated, Union, List

router = APIRouter(tags=["User Management"])


@router.get("/user", response_model=List[User], tags=["User Management"])
async def get_users(
    db: Annotated[Session, Depends(get_db)],
    _: Annotated[UserModel, Depends(current_user)],
) -> List[User]:
    """
    Get All Users
    """
    return await get_all_users(db)


@router.put(
    "/user/{user_id}",
    response_model=User,
    tags=["User Management"],
)
async def update_user(
    user_id: int,
    update_me_user: UpdateMeUser,
    current_user: Annotated[UserModel, Depends(current_user)],
    db: Session = Depends(get_db),
) -> Union[User, HTTPValidationError]:
    """
    Update User information. Only the user themselves or admins can update.
    """
    # Permission check: allow if updating self or if admin/super_admin
    if user_id != current_user.id and current_user.role not in ["ADMIN", "SUPER_ADMIN"]:
        raise HTTPException(status_code=403, detail="Not authorized to update this user")

    updated_user = await update_user_info(db, user_id, update_me_user)
    await add_activity(
        db,
        current_user,
        ActivityTag.UPDATE_PROFILE,
        message=f"User {current_user.full_name} updated {updated_user.full_name}'s info",
    )
    return updated_user


@router.get("/user/me", response_model=User, tags=["User Management"])
async def get_current_user(user: Annotated[UserModel, Depends(current_user)]) -> User:
    """
    Get Current User
    """
    return user
