from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import (
    EmailStr,
)
from sqlmodel import Field, SQLModel


class TokenTypeEnum(str, Enum):
    BEARER = "bearer"
    REFRESH = "refresh"


class RoleTypeEnum(str, Enum):
    USER = "USER"
    SUPER_USER = "SUPER_USER"
    ADMIN = "ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"


class CaseInsensitiveEmailStr(EmailStr):
    @classmethod
    def _validate(cls, email: EmailStr) -> EmailStr:
        email = super()._validate(email)
        return email.lower()


class UserBase(SQLModel):
    # Make id optional so ORM can treat it as autoincrement / generated by DB
    id: Optional[int] = Field(default=None, primary_key=True)
    email: CaseInsensitiveEmailStr = Field(..., description="Email of the user")
    full_name: str = Field(..., description="Name of the user")
    role: RoleTypeEnum = RoleTypeEnum.USER
    status: str = Field(..., description="The user current status")
    last_logged_in: Optional[datetime] = Field(default=None)
    is_temporary_password: bool = Field(default=True)


class UserPublic(UserBase):
    pass


class UserCreate(SQLModel):
    email: CaseInsensitiveEmailStr
    full_name: str
    role: RoleTypeEnum = RoleTypeEnum.USER


class UserSignin(SQLModel):
    email: CaseInsensitiveEmailStr
    password: Optional[str] = None


class UserSigninPublic(SQLModel):
    access_token: str
    refresh_token: str
    user: UserPublic


class PasswordReset(SQLModel):
    email: CaseInsensitiveEmailStr
    password: str
    confirm_password: str
    verification_code: str


class EmailRecipientBase(SQLModel):
    # Make id optional so ORM can treat it as autoincrement / generated by DB
    id: Optional[int] = Field(default=None, primary_key=True, index=True)
    email: CaseInsensitiveEmailStr = Field(..., description="Email of the user")
    name: str = Field(..., description="Name of the user")


class EmailRecipientCreate(SQLModel):
    email: CaseInsensitiveEmailStr
    name: Optional[str] = None


class EmailRecipientPublic(EmailRecipientCreate):
    id: int


class UpdateMeUser(SQLModel):
    full_name: Optional[str] = None
    role: Optional[RoleTypeEnum] = None
    status: Optional[str] = None


# class ActivityLogItem(SQLModel):
#     user: Optional[User] = None
#     user_id: Optional[int] = None
#     activity: Optional[ActivityTag] = None
#     msg: Optional[str] = None
#     timestamp: Optional[datetime] = None
